### ISSUE TITLE
fastpath syntax error at or near "Everbody"

### ISSUE THREAD

**Issue by hellais** [ooni/backend#208]
When running the fastpath against the 2019-09-20 bucket with (PR#213):

I got the following error at some point:
```
607244 90663 DEBUG fastpath Loading nested 2019-09-20/20190920T032401Z-US-AS701-web_connectivity-20190920T032402Z_AS701_scLKevrfoDZVa8rlS4Hkf3rlshGXYNt08DZmTSkR8VRLzz4hLw-0.2.0-probe.json
607264 90663 INFO fastpath load_s3_reports remaining time: 0:02:35.805058
607264 90663 DEBUG fastpath Ingesting web_connectivity.16.tar.lz4
607294 90663 DEBUG fastpath Loading nested 2019-09-20/20190920T032422Z-US-AS7018-web_connectivity-20190920T032425Z_AS7018_5Lb65i9oJ0euLgLavUfnYmT6yT06q3TFRQNyUcEzi78FY7C7fu-0.2.0-probe.json
607550 90663 DEBUG fastpath Loading nested 2019-09-20/20190920T032528Z-BR-AS268400-web_connectivity-20190920T032532Z_AS268400_qOouyQ9CspxTSno7kZj6rW6gIRqBB6ezadsSra4ELiqyWCjKZy-0.2.0-probe.json
607886 90663 DEBUG fastpath Loading nested 2019-09-20/20190920T033152Z-ID-AS17974-web_connectivity-20190920T033153Z_AS17974_O107AIiG8Fz0o8Xw7s6GDmrgTvLswaEDaUP088TsInaF1zrBiE-0.2.0-probe.json
608523 90677 ERROR fastpath syntax error at or near "Everbody"
LINE 1: ...st.com\/category\/local_news_articles\/20100518\/'Everbody-D...
                                                             ^
Traceback (most recent call last):
  File "/Users/x/code/ooni/pipeline/af/fastpath/fastpath/core.py", line 485, in msm_processor
    db.upsert_summary(measurement, summary, tid, fn, conf.update)
  File "/Users/x/.virtualenvs/fastpath/lib/python3.6/site-packages/statsd/client/timer.py", line 38, in _wrapped
    return f(*args, **kwargs)
  File "/Users/x/code/ooni/pipeline/af/fastpath/fastpath/db.py", line 121, in upsert_summary
    cur.execute(q)
psycopg2.errors.SyntaxError: syntax error at or near "Everbody"
LINE 1: ...st.com\/category\/local_news_articles\/20100518\/'Everbody-D...
                                                             ^
```

It did not stall the pipeline, which is great, but is likely something to look into

**Comment by hellais** [comment]
@FedericoCeratto did you look at this? Is it still useful/relevant or should we close it as the code has moved forward?

**Comment by hellais** [comment]
This is no longer relevant. Closing.
