### ISSUE TITLE
Investigate exception in testhelpers.dns_helpers.DNSResolverDiscovery

### ISSUE THREAD

**Issue by hellais** [ooni/backend#76]
There is a particular DNS test helper that is used to discover the IP of the resolver of the user that when run on test machine is getting probed by somebody doing DNS scans (/me thinks) and is triggering these exceptions:

```
Unhandled Error
Traceback (most recent call last):
  File "/root/.virtualenvs/oonib/local/lib/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/root/.virtualenvs/oonib/local/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/root/.virtualenvs/oonib/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/root/.virtualenvs/oonib/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/root/.virtualenvs/oonib/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/root/.virtualenvs/oonib/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 209, in doRead
    return self._dataReceived(data)
  File "/root/.virtualenvs/oonib/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/root/.virtualenvs/oonib/local/lib/python2.7/site-packages/twisted/names/dns.py", line 2853, in dataReceived
    self.controller.messageReceived(m, self)
  File "/root/.virtualenvs/oonib/local/lib/python2.7/site-packages/twisted/names/server.py", line 558, in messageReceived
    self.handleQuery(message, proto, address)
  File "/root/ooni-backend/oonib/testhelpers/dns_helpers.py", line 47, in handleQuery
    payload=dns.Record_A(bytes(address[0]), 0))
exceptions.TypeError: 'NoneType' object has no attribute '__getitem__'
```

Should investigate what this is about.

**Comment by hellais** [comment]
Legacy OONI Probe code, we can close
